"""phase4_schema_expansion

Revision ID: d66a72bf3490
Revises: 9ef3071d0e12
Create Date: 2026-05-22 21:38:52.887293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66a72bf3490'
down_revision: Union[str, None] = '9ef3071d0e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('predicted_action', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('trigger_events', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_predictions_competitor_id'), 'competitor_predictions', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_competitor_predictions_id'), 'competitor_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_competitor_predictions_predicted_action'), 'competitor_predictions', ['predicted_action'], unique=False)
    op.add_column('companies', sa.Column('webhook_url', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('notification_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'notification_email')
    op.drop_column('companies', 'webhook_url')
    op.drop_index(op.f('ix_competitor_predictions_predicted_action'), table_name='competitor_predictions')
    op.drop_index(op.f('ix_competitor_predictions_id'), table_name='competitor_predictions')
    op.drop_index(op.f('ix_competitor_predictions_competitor_id'), table_name='competitor_predictions')
    op.drop_table('competitor_predictions')
    # ### end Alembic commands ###
